# Generated by Django 5.0.4 on 2024-04-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_activated_user_activation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
