# Generated by Django 5.0.4 on 2024-04-14 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default=datetime.datetime(2024, 4, 14, 10, 50, 53, 505744, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
